/*
 * 将.css转换成.js.css，以便使用await import来加载。
 * deno run --allow-read --allow-write CSSTOJS.js
 */
function cssStringToJSString(cssString){
    let js=`// Autogenerated
if(document.styleSheets[0]===undefined){
    let style=document.createElement("style");
    style.type="text/css";
    document.head.appendChild(style);
}
document.styleSheets[0].insertRule(\`
${cssString}
\`);
`;
    return js;
}
async function cssFileToJSFile(cssFile){
    await Deno.writeTextFile(`${cssFile}.js`,cssStringToJSString(await Deno.readTextFile(cssFile)));
}
cssFileToJSFile("./index.html.css");

