/*
 * 将.css转换成.css.js，以便使用await import来加载。
 * deno run --allow-read --allow-write CSSTOJS.js
 */
function cssStringToJSString(cssString){
    let js=`// Autogenerated
let style=document.createElement("style");
style.type="text/css";
style.innerHTML=\`${cssString}\`;
document.head.appendChild(style);
`;
    return js;
}
async function cssFileToJSFile(cssFile){
    await Deno.writeTextFile(`${cssFile}.js`,cssStringToJSString(await Deno.readTextFile(cssFile)));
}
cssFileToJSFile("./index.html.css");
