
// Autogenerated
if(document.styleSheets[0]===undefined){
    let style=document.createElement("style");
    style.type="text/css";
    document.head.appendChild(style);
}
document.styleSheets[0].insertRule(`
#THREE {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow:hidden;
}

`);
