// Autogenerated
let style=document.createElement("style");
style.type="text/css";
style.innerHTML=`#THREE {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow:hidden;
}
`;
document.head.appendChild(style);
