(defun termux::package-install (pkg)
  (let ((symbol (quote termux::*package-refresh-contents*)))
    (unless (boundp symbol)
      (setf (symbol-value symbol) nil))
    (unless (symbol-value symbol)
      (package-refresh-contents)
      (setf (symbol-value symbol) t)))
  (package-install pkg))
(defun termux::emacs-lisp-mode-hook()
  (electric-pair-mode))
(add-hook (quote emacs-lisp-mode-hook) (function termux::emacs-lisp-mode-hook))
(defun termux:fullscreen()
  (interactive)
  (global-auto-revert-mode)
  (show-paren-mode)
  (unless custom-enabled-themes
    (dolist (theme custom-enabled-themes)
      (disable-theme theme))
    (load-theme (quote manoj-dark)))
  (global-font-lock-mode)
  (unless (functionp (function global-company-mode))
    (termux::package-install (quote company)))
  (global-company-mode)
  (unless (functionp (function global-aggressive-indent-mode))
    (termux::package-install (quote aggressive-indent)))
  (global-aggressive-indent-mode))
(global-set-key (kbd "<f11>") (function termux:fullscreen))
(setf package-archives
      (quote
       (("gnu" . "http://mirrors.ustc.edu.cn/elpa/gnu/")
        ("melpa" . "http://mirrors.ustc.edu.cn/elpa/melpa/")
        ("org" . "http://mirrors.ustc.edu.cn/elpa/org/"))))
(unless (and (boundp (quote package--initialized))
             package--initialized)
  (package-initialize))
(defun termux:execute-extended-command()
  (interactive)
  (unless (functionp (function counsel-M-x))
    (termux::package-install (quote ivy))
    (termux::package-install (quote counsel)))
  (call-interactively (function counsel-M-x)))
(global-set-key (kbd "M-x") (function termux:execute-extended-command))
(defun termux:counsel-find-file()
  (interactive)
  (unless (functionp (function counsel-find-file))
    (unless termux::*package-refresh-contents*
      (package-refresh-contents)
      (setf termux::*package-refresh-contents* t))
    (termux::package-install (quote ivy))
    (termux::package-install (quote counsel)))
  (call-interactively (function counsel-find-file)))
(global-set-key (kbd "C-x C-f") (function termux:counsel-find-file))
(defun termux:counsel-dired()
  (interactive)
  (unless (functionp (function counsel-dired))
    (termux::package-install (quote ivy))
    (termux::package-install (quote counsel)))
  (call-interactively (function counsel-dired)))
(global-set-key (kbd "C-x d") (function termux:counsel-dired))
