(defun termux::package-install (pkg)
  "安装elpa包"
  (unless (and (boundp (quote package--initialized))
               package--initialized)
    (setf package-archives
          (quote
           (("gnu" . "http://mirrors.ustc.edu.cn/elpa/gnu/")
            ("melpa" . "http://mirrors.ustc.edu.cn/elpa/melpa/")
            ("org" . "http://mirrors.ustc.edu.cn/elpa/org/"))))
    (package-initialize))
  (let ((symbol (quote termux::*package-refresh-contents*)))
    (unless (boundp symbol)
      (setf (symbol-value symbol) nil))
    (unless (symbol-value symbol)
      (package-refresh-contents)
      (setf (symbol-value symbol) t)))
  (package-install pkg))
(defun termux::emacs-lisp-mode-hook()
  (electric-pair-mode))
(add-hook (quote emacs-lisp-mode-hook) (function termux::emacs-lisp-mode-hook))
(defun termux:fullscreen()
  (interactive)
  (global-auto-revert-mode)
  (show-paren-mode)
  (unless custom-enabled-themes
    (dolist (theme custom-enabled-themes)
      (disable-theme theme))
    (load-theme (quote manoj-dark)))
  (global-font-lock-mode)
  (unless (functionp (function global-company-mode))
    (termux::package-install (quote company)))
  (global-company-mode)
  (unless (functionp (function global-aggressive-indent-mode))
    (termux::package-install (quote aggressive-indent)))
  (global-aggressive-indent-mode)
  (when menu-bar-mode (menu-bar-mode 0)))
(global-set-key (kbd "<f11>") (function termux:fullscreen))
(defun termux::package-install-ivy-counsel-smex ()
  (unless (functionp (function counsel-M-x))
    (termux::package-install (quote ivy))
    (termux::package-install (quote counsel))
    (termux::package-install (quote smex))))
(defun termux:execute-extended-command()
  (interactive)
  (termux::package-install-ivy-counsel-smex)
  (call-interactively (function counsel-M-x)))
(global-set-key (kbd "M-x") (function termux:execute-extended-command))
(defun termux:counsel-find-file()
  (interactive)
  (termux::package-install-ivy-counsel-smex)
  (call-interactively (function counsel-find-file)))
(global-set-key (kbd "C-x C-f") (function termux:counsel-find-file))
(defun termux:counsel-dired()
  (interactive)
  (termux::package-install-ivy-counsel-smex)
  (call-interactively (function counsel-dired)))
(global-set-key (kbd "C-x d") (function termux:counsel-dired))
(defun termux:counsel-switch-buffer()
  (interactive)
  (termux::package-install-ivy-counsel-smex)
  (call-interactively (function counsel-switch-buffer)))
(global-set-key (kbd "C-x b") (function termux:counsel-switch-buffer))
(with-eval-after-load (quote ivy)
  (unless ivy-use-virtual-buffers
    (ivy-mode)
    (setq-default ivy-use-virtual-buffers t
                  ivy-count-format ""
                  projectile-completion-system 'ivy)
    (define-key ivy-minibuffer-map (kbd "RET") (function ivy-alt-done))))
(setf ring-bell-function 'ignore
      (symbol-function 'yes-or-no-p) (symbol-function 'y-or-n-p)
      enable-recursive-minibuffers t)
