(defun HelloWorld (container options)
  (let ((SELF {}))
    (if (=== options undefined) (= options {}))
    (= SELF.container container)
    (if (=== SELF.container undefined)
	(return (console.log "Missing required THREE container.")))
    (= SELF.webGLRenderer (THREE.WebGLRenderer))
    (SELF.container.appendChild SELF.webGLRenderer.domElement)
    (= SELF.scene (THREE.Scene))
    (= SELF.gridHelper (THREE.GridHelper))
    (SELF.scene.add SELF.gridHelper)
    (= SELF.axesHelper (THREE.AxesHelper))
    (SELF.scene.add SELF.axesHelper)
    (= SELF.perspectiveCamera (THREE.PerspectiveCamera))
    (SELF.perspectiveCamera.position.set 10 10 10)
    (= SELF.setSize
       (lambda (width height)
	 (if (=== width undefined) (= width SELF.container.clientWidth))
	 (if (=== height undefined) (= height SELF.container.clientHeight))
	 (SELF.webGLRenderer.setSize width height)
	 (= SELF.perspectiveCamera.aspect (/ width height))
	 (SELF.perspectiveCamera.updateProjectionMatrix)))
    (= SELF.animationFrame
       (lambda ()
	 (SELF.webGLRenderer.render SELF.scene SELF.perspectiveCamera)
	 (= SELF.animationFrameId (requestAnimationFrame SELF.animationFrame))))
    (= SELF.orbitControls (THREE.OrbitControls SELF.perspectiveCamera SELF.webGLRenderer.domElement))
    (SELF.setSize SELF.container.clientWidth SELF.container.clientHeight)
    (SELF.animationFrame)
    SELF))
(= window.APP
   (HelloWorld (document.querySelector "#THREE")))
(window.addEventListener "resize" (lambda () (APP.setSize)))
